### ISSUE TITLE
CODE OF CONDUCT missing

### ISSUE THREAD

**Issue by anjaligoswami** [aryankashyap7/CheatSheets-for-Developers#101]
hey! @aryankashyap7 
code of conduct's markdown file is missing in your repository. If you assign me this issue, then I would like to contribute it in this.

**Comment by anjaligoswami** [comment]
ohh, okay. I didn't know about that.
Thanks for the info.
okay, I am seeing the other issues.  :)

**Comment by SayuriYuto** [comment]
Please close this issue as it cannot be implemented

**Comment by anjaligoswami** [comment]
> Please close this issue as it cannot be implemented

done
