### ISSUE TITLE
A simple website that neatly displays all the cheatsheets here

### ISSUE THREAD

**Issue by Dhravya** [aryankashyap7/CheatSheets-for-Developers#112]
I really like all these cheatsheets, but navigating through Github files is inconvenient. Maybe we can create an astro project that uses the github API to display the markdown of these cheatsheets in a simple website. Hosted on github pages as well. What do you think?

**Comment by aryankashyap7** [comment]
@Dhravya This sounds really interesting. If you would like to work on this upgrade, comment below. I will assign you this Issue. You can then create a new branch and start working on it :)

**Comment by Dhravya** [comment]
Yes! Would be cool.

**Comment by Dhravya** [comment]
Btw, take a look 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/63950637/198286135-5d0848ef-c35a-4d67-b715-dfc2429b7f83.png">

**Comment by aryankashyap7** [comment]
Hey @Dhravya this UI looks good. For now let's continue with the second plan. Just try to restructure the repository in such that it looks well organized.

**Comment by Dhravya** [comment]
Sure!

**Comment by aryankashyap7** [comment]
@Dhravya Just came to check, What's the update with the website?

**Comment by Dhravya** [comment]
Hi! It's done!
