### ISSUE TITLE
Add IoT cheatsheet

### ISSUE THREAD

**Issue by Khushi-Shukla** [aryankashyap7/CheatSheets-for-Developers#138]

**Comment by aryankashyap7** [comment]
@Khushi-Shukla Can you elaborate the topics you are planning to contribute within the IoT domain cheatsheet?

**Comment by Khushi-Shukla** [comment]
> @Khushi-Shukla Can you elaborate the topics you are planning to contribute within the IoT domain cheatsheet?

I am planning to add the following points:
1. A brief introduction
2. How does IoT works
3. IoT and security
4. What does an IoT developer do
5. List of IoT Tools and Platforms for IoT Development and Developers

**Comment by aryankashyap7** [comment]
> > @Khushi-Shukla Can you elaborate the topics you are planning to contribute within the IoT domain cheatsheet?
> 
> I am planning to add the following points:
> 
> 1. A brief introduction
> 2. How does IoT works
> 3. IoT and security
> 4. What does an IoT developer do
> 5. List of IoT Tools and Platforms for IoT Development and Developers

Sounds good enough, Just make sure you make each of those sections descriptive enough to understand the concepts properly. You can even addon the various types of sensors and parts that we use and their descriptions with application in realife projects.
