### ISSUE TITLE
YAML cheat Sheet 

### ISSUE THREAD

**Issue by kiritocode1** [aryankashyap7/CheatSheets-for-Developers#146]
### Added a ***Yaml Cheatsheet*** , im more than happy to update if required , you can see the PR directly [here](https://github.com/aryankashyap7/CheatSheets-for-Developers/pull/145)

**Comment by kiritocode1** [comment]
@aryankashyap7

**Comment by aryankashyap7** [comment]
Sure, That seems like a nice cheat sheet. But prefer doing those changes, I mentioned in your previous PR!
