### ISSUE TITLE
Subheading not properly rendered

### ISSUE THREAD

**Issue by aryankashyap7** [aryankashyap7/CheatSheets-for-Developers#170]
![image](https://user-images.githubusercontent.com/75727351/198822555-8b54316a-43dd-412d-b7c2-3984a16b36f1.png)

As we see in the table of contents, the subheading is not shown properly on the right-hand indexing. So we need some changes such that each header level would be marked as some priority.

eg-

All the headers are with ##
All the subheadings with ###
and so on....

**Comment by aryankashyap7** [comment]
@Dhravya Can you have a look on this?

**Comment by Dhravya** [comment]
Yeah makes sense. I'll try to fix it in a PR today with other small changes. You can assign it to me!
