### ISSUE TITLE
Add Windows Clipboard Shortcut Key

### ISSUE THREAD

**Issue by loretogutierrezjr** [aryankashyap7/CheatSheets-for-Developers#18]
Hi,
I would like to add a very handy shortcut key for Windows to view the Clipboard.
Win + V
This will show all the copied text and used it multiple times in clipboard app.

**Comment by aryankashyap7** [comment]
It's really a good feature, that I missed mentioning. Sure, You can add it! Just make sure to add it to the right section and incase I missed few more, you can add them too :)

**Comment by loretogutierrezjr** [comment]
> It's really a good feature, that I missed mentioning. Sure, You can add it! Just make sure to add it to the right section and incase I missed few more, you can add them too :)

hi aryan,
I just add it.. please check if possible to merge? Thanks
