### ISSUE TITLE
Adding Git naming conventions to Cheat Sheet (fix, feat, chore, docs, etc.)

### ISSUE THREAD

**Issue by aryanprince** [aryankashyap7/CheatSheets-for-Developers#192]
In the git.md, we could mention some lightweight conventions for git commit messages as a lot of professional codebases follow these. Like including fix, feat, chore, docs at the beginning of the commit messages.

Format:
```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

Some examples: 
- feat: allow provided config object to extend other configs
- docs: correct spelling of CHANGELOG
- fix: prevent racing of requests

Source: [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

@aryankashyap7 Thoughts?

**Comment by aryankashyap7** [comment]
Hi @aryanprince Thanks for creating this issue, But I don't this we actually have a necessity for this in our cheatsheets. It won't bring any major change.
