### ISSUE TITLE
Update windows.md file

### ISSUE THREAD

**Issue by nakul010** [aryankashyap7/CheatSheets-for-Developers#215]
- I want to add some more shortcuts in this file.
- I want to change the appearance of commands(second image) as seen in first image

![image](https://user-images.githubusercontent.com/98902181/199009140-0b3fcc85-c316-423d-831f-0aa1eaac00c7.png)
-----------------------------------------
![image](https://user-images.githubusercontent.com/98902181/199008466-d55b7ca7-159b-47e6-bc24-75668b2044b1.png)

**Comment by aryankashyap7** [comment]
Thanks for your interest in our project. But we can't take this contribution acceptable for the hacktoberfest tag

**Comment by nakul010** [comment]
@aryankashyap7, no i don't want to contribute under hacktoberfest tag. I just want to contribute in general.

**Comment by aryankashyap7** [comment]
Then I'm glad to assign you this task :)
