### ISSUE TITLE
Vue.js commands error on cheats.dhr.wtf

### ISSUE THREAD

**Issue by aryanprince** [aryankashyap7/CheatSheets-for-Developers#225]
Just me or the Vue commands look 'blank' on [https://cheats.dhr.wtf/sheet/vuejs/](https://cheats.dhr.wtf/sheet/vuejs/)?  `vuejs.md` file looks okay

How it looks like for me

![image](https://user-images.githubusercontent.com/45622345/199267259-be4949e2-5301-42c3-8403-35fe4fb934bc.png)

**Comment by aryankashyap7** [comment]
Yes @aryanprince, It seems like there are some bugs, we need to use some other container parameter to show these values :)

**Comment by Dhravya** [comment]
That's interesting, i think the browser is trying to render the code block??? Does anyone else know what's going on? lol
<img width="457" alt="image" src="https://user-images.githubusercontent.com/63950637/199277584-e9b08efb-e7cc-4ccb-860a-d4954ed9fa83.png">
