### ISSUE TITLE
Incorrect markdown formatting for table in Mysql

### ISSUE THREAD

**Issue by Dhravya** [aryankashyap7/CheatSheets-for-Developers#232]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/63950637/211548981-e9366908-8164-4041-be46-4d5ac31995bc.png">

This happens right after `Delete table` - https://cheats.dhr.wtf/sheet/mysql/#delete-table

**Comment by aryankashyap7** [comment]
@Dhravya This issue has been resolved, Make sure you don't forget to pull the latest version.

Well, it's better to close all the PRs that haven't been resolved yet as the users working on it are inactive after Hacktoberfest. Whats your opinion?

**Comment by Dhravya** [comment]
Alright! and yeah, we should close the PRs
