### ISSUE TITLE
Can You providing links of Video tutorial of each tech stack within their cheatsheet.

### ISSUE THREAD

**Issue by manu-prakash-choudhary** [aryankashyap7/CheatSheets-for-Developers#233]
The video will mainly consists of brief demonstration of properties related to each tech stack

**Comment by aryankashyap7** [comment]
Thanks for your suggestion, But we have already thought of it. But implementing it wasn't feasible as it may always differ from person to person, whether they would like a content creator. So the main idea was to without moving to any other page, we could find all the details of that language.
