### ISSUE TITLE
Vue.js Cheatsheet

### ISSUE THREAD

**Issue by protob** [aryankashyap7/CheatSheets-for-Developers#24]
Hi,
I can contribute by adding Vue.js Cheatsheet.

**Comment by aryankashyap7** [comment]
Sure, You can start working on it!!

**Comment by ultr4nerd** [comment]
Hey, can I help?

**Comment by aryankashyap7** [comment]
@ultr4nerd Sure, You can work on it too :)

**Comment by protob** [comment]
I will create my pull request in the evening today

**Comment by aryankashyap7** [comment]
@protob Sure, Would be waiting for it!

**Comment by ultr4nerd** [comment]
@protob I wait for you so I can add more content

**Comment by aryankashyap7** [comment]
@ultr4nerd You can now work on the updates. the previously assigned user has already contributed their changes a few hours ago!
