### ISSUE TITLE
Add Python Cheatsheet.md

### ISSUE THREAD

**Issue by TimTemi** [aryankashyap7/CheatSheets-for-Developers#4]
Assign me this task

**Comment by aryankashyap7** [comment]
Sure, you can start working on it! :)

**Comment by TimTemi** [comment]
@aryankashyap7 , great! I'll do that.

**Comment by Atharv-777** [comment]
hey @aryankashyap7 Can i add 3 more String functions to python-cheatsheet.md file

**Comment by Atharv-777** [comment]
@aryankashyap7 functions like : 
<str>.center(<int>, <char>)
<str>.center(<int>, <char>)
<str>.center(<int>, <char>)
