### ISSUE TITLE
Competitive Programming cheatsheet.

### ISSUE THREAD

**Issue by Dhruvil-Lakhtaria** [aryankashyap7/CheatSheets-for-Developers#43]
It will contain standard competitive snippets and algorithm code. 
Can you please assign me this under hacktoberfest.

**Comment by aryankashyap7** [comment]
Sure that looks great, You can start working on it. Make sure you follow the same template as other cheatsheet files do. You can check out CONTRIBUTIONS.md for a more detailed analysis. 

Regarding the hacktoberfest label, No worries during your PR submission. I would mark that label :)

**Comment by zender651** [comment]
I would also like to contribute regarding some algo and snippets

**Comment by nishant3721** [comment]
@aryankashyap7 I would like to work on this issue!?

**Comment by aryankashyap7** [comment]
@Dhruvil-Lakhtaria Are you still working on this issue? , I would be waiting for your reply within 2 hours. Then I would assign this topic to someone else.

**Comment by aryankashyap7** [comment]
@zender651 In case you would like to add some more valuable contributions, you can do now. I'm assigning you this issue.

**Comment by jrenzzo** [comment]
@aryankashyap7 Hello! I would like to contribute regarding containers in the section of STL.

**Comment by aryankashyap7** [comment]
@jrenzzo Can you elaborate more, what are the changes you are planning to do?

**Comment by jrenzzo** [comment]
@aryankashyap7  Containers in STL are a collection of objects of a specific type. They are widely used in competitive programming. It includes vector, array, list, deque, list, etc. This section is missing in the cheatsheet and I would like to add it.

**Comment by aryankashyap7** [comment]
@jrenzzo Actually these concepts have already been added in the `cpp stl cheatsheet` have a look at them, Then let me know is that any thing different you are planning to implement. Specifically for the Competative Programming Cheatsheet!

**Comment by pavalucas** [comment]
Hello! I would like to add string matching algorithms.

**Comment by aryankashyap7** [comment]
Hi @pavalucas for this particular cheatsheet we prefer contributions from someone who have long time experience with competitive programming. Can you share the achievements/profile links of your  s (Codeforces/Codechef/Leetcode)

**Comment by pavalucas** [comment]
> Hi @pavalucas for this particular cheatsheet we prefer contributions from someone who have long time experience with competitive programming. Can you share the achievements/profile links of your s (Codeforces/Codechef/Leetcode)

@aryankashyap7 sure! I participated in ACM ICPC competitions during my 5 years of undergrad. Here are some achievements:
- 11th/60 in 2019 and 26th/72 in 2017 in the ACM ICPC Brazil Final.
- 3th out of 35 teams in 2017 Microsoft Coding Challenge, Rio de Janeiro.
- 146th out of 1119 contestants in the 2015 Brazilian Olympiad in Informatics - undergraduate level.

Also, here are my profile links:
- [Codeforces](https://codeforces.com/profile/Gunnalar): Expert - 1658 rating.
- [Leetcode](https://leetcode.com/Gunnalar/): 186 problems solved.
- [Codechef](https://www.codechef.com/users/pavalucas): 1697 rating.

**Comment by aryankashyap7** [comment]
@pavalucas Glad to assign you this topic, You can make the changes that you feel necessary 🙂

**Comment by Dhravya** [comment]
@pavalucas are you still working on this?
