### ISSUE TITLE
Add PHP Cheatsheet

### ISSUE THREAD

**Issue by RenithaK** [aryankashyap7/CheatSheets-for-Developers#5]
Kindly assign me this issue.

**Comment by RenithaK** [comment]
Done @aryankashyap7

**Comment by aryankashyap7** [comment]
Check your PR again, you uploaded a blank file!

**Comment by RenithaK** [comment]
Yes, you can review the updated one @aryankashyap7 

There were some issues in the old branch, so it got uploaded as an empty one.

Check the updated one in a new branch:

https://github.com/aryankashyap7/CheatSheets-for-Developers/pull/22
