### ISSUE TITLE
Python Keywords

### ISSUE THREAD

**Issue by Ns-SheF** [aryankashyap7/CheatSheets-for-Developers#51]

**Comment by Ns-SheF** [comment]
A cheatsheet that explains common keywords in python (like -- if, else, elif; for; return; dev; class etc) with an example of how it is used.

**Comment by aryankashyap7** [comment]
Sure you can modify those aspects, but for this control statements topics. Add it to the proper index i.e before the Advanced Topics section and update some mistakes with the numbering of topics (Check out the subtopics numbering of point 3).

**Comment by Ns-SheF** [comment]
Alright. thanks.......................

**Comment by prabhleenn** [comment]
Hey ! I would love to work on this by making my first Hacktoberfest submission.
It would be great if you assign me this.

**Comment by aryankashyap7** [comment]
@Ns-SheF Are you still working on this issue, incase not I will assign to someone else. Would be waiting for your response, for the next 2 hours!

**Comment by aryankashyap7** [comment]
@prabhleenn You can contribute to this issue :)

**Comment by Ns-SheF** [comment]
ahhh.  32 mins. Okay.
Sorry had other engagements but was done with the indexing. File was looking scary.

No problems tho.  Will try to be punctual more.

**Comment by aryankashyap7** [comment]
@Ns-SheF Not an issue, You both can work on the task. But remember to pull the new changes to your forked repo, As I have fixed those bugs regarding the indexing myself :)
