### ISSUE TITLE
Add MacOS Commands CheatSheet

### ISSUE THREAD

**Issue by aryankashyap7** [aryankashyap7/CheatSheets-for-Developers#53]

**Comment by samarth777** [comment]
Can u assign this to me

**Comment by loretogutierrezjr** [comment]
hi Aryan, 
I didn't see this post.. I open an issue for this.
Can I work on this? Thanks

**Comment by loretogutierrezjr** [comment]
Hi Aryan,
Please check I've submitted my pullrequest for this topic. Thanks.
