### ISSUE TITLE
Add Deep Learning CheatSheet

### ISSUE THREAD

**Issue by aryankashyap7** [aryankashyap7/CheatSheets-for-Developers#58]

**Comment by Ananya2003Gupta** [comment]
Can I work on this?

**Comment by divyang9575** [comment]
okay please assign me this task. I would love to work on it.

**Comment by aryankashyap7** [comment]
@divyang9575 You can start working on it. Make sure to check out the `Machine Learning Cheatsheet` for a clear idea.
