### ISSUE TITLE
Modifications Required in Java Cheat Sheet

### ISSUE THREAD

**Issue by aryankashyap7** [aryankashyap7/CheatSheets-for-Developers#70]
**The issue is that there are some sections missing, so some addons are required:**

1. Various ways to Input and Output
2. Array and ArrayList
3. String and StringBuilder
4. String Tokenizer

**Comment by TheCodeAlpha26** [comment]
Hey @aryankashyap7 , Please Assign this to me

**Comment by aryankashyap7** [comment]
Sure you can start working on it :)

**Comment by RiyaBhaskar12** [comment]
hey @aryankashyap7 , please assign this issue to me too!

**Comment by aryankashyap7** [comment]
@RiyaBhaskar12 Sure, you can work on this topic. But make sure to pull the recent updates from the repo before you start working on it. 

You can add these sections over there:

1. Input / Output Methods
2. Functions that used with Arrays

Feel free to add more sections that you prefer!

**Comment by loretogutierrezjr** [comment]
hi, can I add my contributions on this? Thanks

**Comment by RiyaBhaskar12** [comment]
I've made the changes in Java Cheatsheet and added the Methods in java. But its shows the following and i'm unable to commit.

"""
 git status
On branch main
Your branch is up to date with 'origin/main'.
"""

**Comment by aryankashyap7** [comment]
@RiyaBhaskar12 It seems like you have not pulled the updated changes into your repository. If you are using Git Bash CLI,

Use the command 

`git pull` 

Make sure before you do that, you must go to your [forked repository](https://github.com/RiyaBhaskar12/CheatSheetsforDevelopers) and use the sync fork option to pull the changes to your own forked repo.

![image](https://user-images.githubusercontent.com/75727351/198025350-6d7d69af-d32c-4dba-8b94-abf6df132a51.png)



**In case the problem still persists,** you can directly upload the changes via GitHub. Just go to your forked repository and open the `java-cheatsheet.md` file. There you can find the edit file option. You can make the changes and create a PR from there.

![image](https://user-images.githubusercontent.com/75727351/198026237-94791cf6-b4e1-41d4-8823-8d38def41ece.png)

**Comment by RiyaBhaskar12** [comment]
yeah, i've added them directly. . please check and revert

**Comment by divyang9575** [comment]
can you please assign this task to me.

**Comment by divyang9575** [comment]
@aryankashyap7  Yes sir, I've added the various methods of I/O section to the cheatsheet.
