### ISSUE TITLE
Improvement in C++ STL

### ISSUE THREAD

**Issue by anjaligoswami** [aryankashyap7/CheatSheets-for-Developers#77]
Hey! It would be good to add some website link and video links as well. for those who are not into reading much.

please assign this issue to me, if u think its worth adding.

**Comment by aryankashyap7** [comment]
Hey @anjaligoswami the motive of this cheat sheet is to avail all the necessary information, without making the user surf other sites. Although it's a good idea to add a website and video links but these are usually not preferred in cheatsheets as every person has their own preferences.

Apart from that, you can contribute the various functions used in C++ Stl data structures, their applications, time complexity and space complexity. I'm assigning this issue to you, lemme know your thoughts :)

**Comment by anjaligoswami** [comment]
yep, make sense.
okay, I am adding other stuff. Thanks for assigning this issue to me

**Comment by divyang9575** [comment]
Hey I can add some improvements in the cheatsheet.

**Comment by aryankashyap7** [comment]
> Hey I can add some improvements in the cheatsheet.

Hey @divyang9575 you can create a new issue and mention the changes you would like to contribute. Then we can discuss this further.
