### ISSUE TITLE
github issue

### ISSUE THREAD

**Issue by divyang9575** [aryankashyap7/CheatSheets-for-Developers#85]
I am new to github, please can you tell me how to upload the cheatsheet

**Comment by aryankashyap7** [comment]
Hi Divyang, Glad to see you have created your pr. The steps were already mentioned in the `CONTRIBUTIONS.md` you could have read the documentation.

Contributions are what make the open source community such an amazing place to be learn, inspire, and create. Any contributions you make are greatly appreciated.

Steps are:

1. Fork this repository.
2. Clone your forked copy of the project(git clone https://github.com/Your-User-Name/CheatSheets-for-Developers.git)
3. Navigate to the project directory(cd CheatSheets-for-Developers)
4. Create a new branch(git checkout -b YourBranchName)
5. Make changes in the source code.
6. Stage your changes(git add .) & commit your changes( git commit -m "<your_commit_message>")
7. Push your local commits to the remote repo( git push origin YourBranchName)
8. Create a PR
